### ISSUE TITLE
POM files, they actually point to 10.6 instead of 10.7

### ISSUE THREAD

**Issue by cdufault** [Esri/kafka-for-geoevent#20]
The 10.7.1 pom file points to 10.6 version. 
![image](https://user-images.githubusercontent.com/4854714/69447606-b4f55600-0d0b-11ea-86ed-d1ffceaa5c1a.png)

**Comment by eironside** [comment]
As of 2019, we no longer update custom connectors for the GeoEvent releases. Unless otherwise noted, a connector compiled against an older version of the GeoEvent SDK should be forward compatible. This is true for anything that is 10.4.0 or later.
